# Secret must be applied first before deployment
# if deployment is referencing value from secret
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # dont write secret as plain text
  # both are base64 encoded
  # username: root
  # password: example
  # to create it, use echo -n 'root' | base64 then paste the value here
  mongo-root-username: cm9vdA==
  mongo-root-password: ZXhhbXBsZQ==
